root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/bot/main.go"
bin = "./tmp/main"

include_ext = ["go", "json"]
exclude_dir = ["tmp", "build", "vendor", "log"]

stop_on_error = true

delay = 1000 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
