[tools]
go = "1.25.1"
air = "1.63.0"
"aqua:golangci/golangci-lint" = "2.5.0"

[tasks.install]
description = "Install dependencies"
run = ["go mod tidy", "go mod vendor"]

[tasks.dev]
description = "Run the app locally with live-reloading"
run = "air"

[tasks.build]
description = "Build the app"
run = "go build -o build/main.exe cmd/bot/main.go"

[tasks.lint]
description = "Format & lint"
run = ["golangci-lint fmt", "golangci-lint run --fix --fast-only"]

# [tasks.lint-ps]
# description = "Lint PowerShell scripts"
# run = [
#   "Invoke-ScriptAnalyzer -Path dev.ps1",
#   "(Get-Content dev.ps1 -Raw | Invoke-Formatter) | Set-Content dev.ps1",
# ]
